config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :users
  resources :posts, only: [:new, :create, :index]
  resources :authors
  resources :user_sessions, only: %i[new create destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  validates :title, presence: true, length: { minimum: 2 }
  validates :post, presence: true, length: { in: 1..500 }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :post
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?
  def current_user
    @current_user ||= User.find_by_id(session[:user])
  end

   def logged_in?
     current_user != nil
   end

  def require_login
    unless logged_in?
      flash.now[:error] = "You must be logged in to access this section"
      redirect_to new_post_path
    end 
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # before_action :require_login, only: [:new, :create]

  def new
    @post = Post.new
  end


  def create
    @post = Post.new(post_params)
    @post.save
    flash.notice = "Post '#{@post.title}' Created!"
    redirect_to posts_path
  end

  def index
    @posts = Post.all
  end
end

 private
 def post_params

params.require(:post).permit(:title, :post )

 end

app/controllers/users_controller.rb
class UsersController < ApplicationController

def index

  @users= User.all

end


  def new
    @user = User.new
  end


  def create

    @user = User.new(user_params)
    @user.save


    redirect_to users_path
  end


end

 private

def set_user
    @user = User.find(params[:id])
  end


 def user_params

params.permit(:username, :password )


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper



end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MembersOnly</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<h1>Index</h1>

<ul id="posts">
<% @posts.each do |post| %>
 <li>
<%= link_to post.title, posts_path(post), class: 'post_title' %>
</li>
<% end %>
</ul>
<%= link_to 'Create a new post', new_post_path, class: 'new_post' %>

app/views/posts/new.html.erb
<h1>New</h1>
<%= form_for @post do |f| %>
  <div>
    <%= f.label :title, 'Title' %><br>
    <%= f.text_field :title, placeholder: "Title" %>
  </div>
  <br>
  <div>
    <%= f.label :post %><br>
    <%= f.text_area :post, placeholder: "Write your opinions here" %>
  </div>
  <%= f.submit("Submit the Post")%>


<% end %>


  

app/views/users/index.html.erb
<h1>Index</h1>

<h1>Login</h1>

<%= form_tag user_sessions_path, method: :post do %>
  <div class="field">
    <%= label_tag :username %>
    <%= text_field_tag :username %>
    <br/>
  </div>
  <div class="field">
    <%= label_tag :password %>
    <%= password_field_tag :password %>
    <br/>
  </div>
  <div class="actions">
    <%= submit_tag "Login" %>
  </div>
<% end %>

<%= link_to 'Back', posts_path %>


<%= link_to 'Create a new post', new_post_path, class: 'new_post' %>

app/views/users/new.html.erb
<%= form_with(url: "/users", local: true) do |form| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% users.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :username %>
    <%= form.text_field :username %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>